LiuggioHelpDeskTicketSystemBundle_customer_care_ticket:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/ticket.yml"
    prefix:   /ticket

LiuggioHelpDeskTicketSystemBundle_customer_care_coment:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

LiuggioHelpDeskTicketSystemBundle_customer_care_operator_ticket:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/ticket_operator.yml"
    prefix:   /operator/ticket

LiuggioHelpDeskTicketSystemBundle_customer_care_operator_coment:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/comment_operator.yml"
    prefix:   /operator/comment