LiuggioHelpDeskBundle_customer_care_ticket:
    resource: "@LiuggioHelpDeskBundle/Resources/config/routing/user.yml"
    prefix:   /

LiuggioHelpDeskBundle_customer_care_operator_ticket:
    resource: "@LiuggioHelpDeskBundle/Resources/config/routing/operator.yml"
    prefix:   /operator
