Liuggio\HelpDeskBundle\Model\Ticket:
    properties:
        subject:
            - NotNull: ~
        body:
            - NotNull: ~
        language:
            - NotNull: ~

Liuggio\HelpDeskBundle\Model\BaseComment:
    properties:
        body:
            - NotNull: ~