<?php

namespace Liuggio\HelpDeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function findByOperator($operator)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('c')
            ->from('LiuggioHelpDeskBundle:Category', 'c')
            ->innerJoin('c.operators', 'opr')
            ->leftJoin('opr.operator','user_operator')
            ->where('user_operator = :user')
            ->setParameter('user', $operator);

        return $qb->getQuery()->getResult();
    }


}