comment_create_admin:
    pattern:  /create
    defaults: { _controller: "LiuggioHelpDeskBundle:CommentOperator:create", state: 'replied', redirectTo: 'ticket_show_admin' }
    requirements: { _method: post }
