ticket_admin:
    pattern:  /{state}
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:TicketAdmin:index", state: open }
    requirements:
      state: open|closed
      _method: get

ticket_search_admin:
    pattern:  /{state}/search/
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:TicketAdmin:index", state: open}
    requirements:
      state: open|closed|all
      _method: get

ticket_show_admin:
    pattern:  /{id}/show
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:TicketAdmin:show" }
