ticket:
    pattern:  /{status}
<<<<<<< HEAD
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:index", status: open }
    requirements:
      status: open|closed|all
=======
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:index", status:open }
    requirements: { status: open|close|all }

>>>>>>> 23d6dda872222a39cfda4d05f6582dab87b03527

ticket_show:
    pattern:  /{id}/show
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:show" }

ticket_new:
    pattern:  /new
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:new" }

ticket_create:
    pattern:  /create
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:create" }
    requirements: { _method: post }

ticket_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:edit" }

ticket_update:
    pattern:  /{id}/update
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:update" }
    requirements: { _method: post }

ticket_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:delete" }
    requirements: { _method: post }

ticket_close:
    pattern:  /{id}/close
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:close" }
    requirements: { _method: post }
    
ticket_rate:
    pattern:  /rate
    defaults: { _controller: "LiuggioHelpDeskTicketSystemBundle:Ticket:rate" }
    requirements: { _method: post }