LiuggioHelpDeskBundle_customer_care_ticket:
    resource: "@LiuggioHelpDeskBundle/Resources/config/routing/user/ticket.yml"
    prefix:   /ticket

LiuggioHelpDeskBundle_customer_care_coment:
    resource: "@LiuggioHelpDeskBundle/Resources/config/routing/user/comment.yml"
    prefix:   /comment